### ISSUE TITLE
🚀 Feature: Swift Support

### ISSUE THREAD

**Issue by Kilo-Loco** [appwrite/runtimes#62]
### 🔖 Feature description

We should support Swift as a runtime for functions.

### 🎤 Pitch

The Apple community is dedicated to the Swift programming language and allowing them to write functions in their preferred programming language is something that would benefit that community. It also makes Appwrite stand out from the competition because Swift is generally not offered for writing functions by other BaaS products.

open-runtimes currently supports 2 versions of Swift:
| Swift | 5.5 | [openruntimes/swift:v3-5.5](https://hub.docker.com/r/openruntimes/swift) | [Examples](/runtimes/swift-5.5/example) | [![Docker Pulls](https://img.shields.io/docker/pulls/openruntimes/swift?color=f02e65&style=flat-square)](https://hub.docker.com/r/openruntimes/swift) |
| Swift | 5.8 | [openruntimes/swift:v3-5.8](https://hub.docker.com/r/openruntimes/swift) | [Examples](/runtimes/swift-5.8/example) | [![Docker Pulls](https://img.shields.io/docker/pulls/openruntimes/swift?color=f02e65&style=flat-square)](https://hub.docker.com/r/openruntimes/swift) |

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/appwrite/appwrite/blob/HEAD/CODE_OF_CONDUCT.md)

**Comment by eldadfux** [comment]
Swift is already supported. We do plan to introduce it on Cloud later on.
![image](https://github.com/appwrite/runtimes/assets/1297371/a48c22c1-c32a-4cf3-9fc8-8c0da74ab9e3)
